"""quiz explanation ustuni

Revision ID: 5901e26033b8
Revises: a3d2475bb7dc
Create Date: 2026-09-26 14:45:29.279510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5901e26033b8'
down_revision: Union[str, Sequence[str], None] = 'a3d2475bb7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('explanation', sa.String(length=2000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'explanation')
    # ### end Alembic commands ###
