"""courses is_pro qo'shildi

Revision ID: a329d8e16de6
Revises: 24794fd22f19
Create Date: 2026-09-25 17:34:34.227785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a329d8e16de6'
down_revision: Union[str, Sequence[str], None] = '24794fd22f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    'courses',
    sa.Column(
        'is_pro',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_pro')
    # ### end Alembic commands ###
