"""quiz_questions jadvali

Revision ID: a3d2475bb7dc
Revises: 36267930f731
Create Date: 2026-09-26 13:22:55.062823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d2475bb7dc'
down_revision: Union[str, Sequence[str], None] = '36267930f731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('option_a', sa.String(length=500), nullable=False),
    sa.Column('option_b', sa.String(length=500), nullable=False),
    sa.Column('option_c', sa.String(length=500), nullable=False),
    sa.Column('option_d', sa.String(length=500), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_lesson_id'), 'quiz_questions', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_questions_lesson_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    # ### end Alembic commands ###
